In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score, mean_squared_error
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np

df = pd.read_csv("Student_Marks.csv")
df

    number_courses  time_study   Marks
0                3       4.508  19.202
1                4       0.096   7.734
2                4       3.133  13.811
3                6       7.909  53.018
4                8       7.811  55.299
..             ...         ...     ...
95               6       3.561  19.128
96               3       0.301   5.609
97               4       7.163  41.444
98               7       0.309  12.027
99               3       6.335  32.357

[100 rows x 3 columns]

In [ ]:
df.isnull().sum()

number_courses    0
time_study        0
Marks             0
dtype: int64

In [ ]:
df.dropna(inplace=True)
df.isnull().sum()

number_courses    0
time_study        0
Marks             0
dtype: int64

In [ ]:
df.dropna(inplace=True)

In [ ]:
df

    number_courses  time_study   Marks
0                3       4.508  19.202
1                4       0.096   7.734
2                4       3.133  13.811
3                6       7.909  53.018
4                8       7.811  55.299
..             ...         ...     ...
95               6       3.561  19.128
96               3       0.301   5.609
97               4       7.163  41.444
98               7       0.309  12.027
99               3       6.335  32.357

[100 rows x 3 columns]

In [ ]:
df.head()

   number_courses  time_study   Marks
0               3       4.508  19.202
1               4       0.096   7.734
2               4       3.133  13.811
3               6       7.909  53.018
4               8       7.811  55.299

In [ ]:
# plt.scatter(df['CGPA'], df['Attendance_Rate'])
# plt.xlabel('CGPA')
# plt.ylabel('Attendance_Rate')

In [ ]:
# X = df.iloc[:,6]
# Y = df.iloc[:,-8]

In [ ]:
# X

In [ ]:
# Y

In [ ]:
# X_train , X_test , Y_train, Y_test = train_test_split(X , Y , test_size=0.2 , random_state=2)

In [ ]:
# lr = LinearRegression

In [ ]:
# X_test

In [ ]:
# Y_test

In [3]:
x = df.iloc[:,1].values
y = df.iloc[:,2].values

NameError: name 'df' is not defined

In [ ]:
x

array([4.508, 0.096, 3.133, 7.909, 7.811, 3.211, 6.063, 3.413, 4.41 ,
       6.173, 7.353, 0.423, 4.218, 4.274, 2.908, 4.26 , 5.719, 6.08 ,
       7.711, 3.977, 4.733, 6.126, 2.051, 4.875, 3.635, 1.407, 0.508,
       4.378, 0.156, 1.299, 3.864, 1.923, 0.932, 6.594, 4.083, 7.543,
       2.966, 7.283, 6.533, 7.775, 0.14 , 2.754, 3.591, 1.557, 1.954,
       2.061, 3.797, 4.779, 5.635, 3.913, 6.703, 4.13 , 0.771, 6.049,
       7.591, 2.913, 7.641, 7.649, 6.198, 7.468, 0.376, 2.438, 3.606,
       4.869, 0.13 , 2.142, 5.473, 0.55 , 1.395, 3.948, 3.736, 2.518,
       4.633, 1.629, 6.954, 0.803, 6.379, 5.985, 7.451, 0.805, 7.957,
       2.262, 7.41 , 3.197, 1.982, 6.201, 4.067, 1.033, 1.803, 6.376,
       4.182, 2.73 , 5.027, 6.471, 3.919, 3.561, 0.301, 7.163, 0.309,
       6.335])

In [ ]:
y

array([19.202,  7.734, 13.811, 53.018, 55.299, 17.822, 29.889, 17.264,
       20.348, 30.862, 42.036, 12.132, 24.318, 17.672, 11.397, 19.466,
       30.548, 38.49 , 50.986, 25.133, 22.073, 35.939, 12.209, 28.043,
       16.517,  6.623, 12.647, 26.532,  9.333,  8.837, 24.172,  8.1  ,
       15.038, 39.965, 17.171, 43.978, 13.119, 46.453, 41.358, 51.142,
        7.336, 15.725, 19.771, 10.429,  9.742,  8.924, 16.703, 22.701,
       26.882, 19.106, 40.602, 22.184,  7.892, 36.653, 53.158, 18.238,
       53.359, 51.583, 31.236, 51.343, 10.522, 10.844, 19.59 , 21.379,
       12.591, 13.562, 27.569,  6.185,  8.92 , 21.4  , 16.606, 13.416,
       20.398,  7.014, 39.952,  6.217, 36.746, 38.278, 49.544,  6.349,
       54.321, 17.705, 44.099, 16.106, 16.461, 39.957, 23.149,  6.053,
       11.253, 40.024, 24.394, 19.564, 23.916, 42.426, 24.451, 19.128,
        5.609, 41.444, 12.027, 32.357])

In [ ]:
x_train , x_test , y_train, y_test = train_test_split(X , Y , test_size=0.2 , random_state=2)

In [ ]:
x_train

487    3.63
219    3.34
422    2.04
742    2.88
636    3.57
       ...
596    2.46
652    2.94
552    3.11
589    2.17
187    2.44
Name: CGPA, Length: 744, dtype: float64

In [1]:
x_train.shape

NameError: name 'x_train' is not defined